name: HAPcryst
version: 0.1.11dev
date: 2013-10-27
description: |
    A HAP extension for crytallographic groups

authors:
    - name: Marc Roeder
      url: http://csserver.evansville.edu/~mroeder

maintainers:
    - name: Marc Roeder
      url: http://csserver.evansville.edu/~mroeder
    - name: The GAP Team
      url: mailto:support@gap-system.org

GAP: ">=4.4.10"

needed-pkgs:
    - name: "Polycyclic"
      version: ">=2.8.1"
      url: "https://gap-packages.github.io/polycyclic/"
    - name: "AClib"
      version: ">=1.1"
      url: "https://gap-packages.github.io/aclib/"
    - name: "cryst"
      version: ">=4.1.5"
      url: "https://www.math.uni-bielefeld.de/~gaehler/gap45/packages.php"
    - name: "HAP"
      version: ">=1.8"
      url: "http://hamilton.nuigalway.ie/Hap/www"
    - name: "polymaking"
      version: ">=0.7.9"
      url: "https://gap-packages.github.io/polymaking/"

suggested-pkgs:
    - name: "Carat"
      version: ">=1.1"
      url: "https://www.math.uni-bielefeld.de/~gaehler/gap/packages.php"
    - name: "CrystCat"
      version: ">=1.1.2"
      url: "https://www.math.uni-bielefeld.de/~gaehler/gap45/packages.php"
    - name: "GAPDoc"
      version: ">= 0.99"
      url: "http://www.math.rwth-aachen.de/~Frank.Luebeck/GAPDoc"

www: https://gap-packages.github.io/hapcryst/
readme: README.md
packageinfo: https://gap-packages.github.io/hapcryst/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/gap-packages/hapcryst/releases/download/v0.1.11dev/hapcryst-0.1.11dev.tar.gz

abstract: |
    This is an extension to the HAP package by Graham Ellis. It implements geometric methods for the calculation of resolutions of Bieberbach groups.

status: deposited
doc-html: doc/chap0.html
doc-pdf: doc/manual.pdf
keywords: |
    homological algebra, crystallographic groups, resolution.
citeas: |
    <p class='BibEntry'>
    [<span class='BibKey'>RT13</span>]   <b class='BibAuthor'>Roeder, M. and GAP Team, T.</b>,
     <i class='BibTitle'>HAPcryst, A HAP extension for crytallographic groups,
             Version 0.1.11dev</i>
     (<span class='BibYear'>2013</span>)<br />
    (<span class='BibNote'>GAP package</span>),
    <span class='BibHowpublished'><a href="https://gap-packages.github.io/hapcryst/">https://gap-packages.github.io/hapcryst/</a></span>.
    </p>
    

bibtex: |
    @misc{ HAPcryst0.1.11dev,
      author =           {Roeder, M. and GAP Team, T.},
      title =            {{HAPcryst}, A HAP extension for crytallographic groups, {V}ersion 0.1.11dev},
      month =            {Oct},
      year =             {2013},
      note =             {GAP package},
      howpublished =     {\href {https://gap-packages.github.io/hapcryst/} {\texttt{https://gap-packages.github.io/}\discretionary {}{}{}\texttt{hapcryst/}}},
      keywords =         {homological algebra; crystallographic groups; resolution},
      printedkey =       {RT13}
    }

